// SPDX-License-Identifier: MIT
//
// Self-contained SQL dumps (MySQL + PostgreSQL).
//   - DROP TABLE IF EXISTS in FK-safe order: district, city, region.
//   - MySQL: utf8mb4 / utf8mb4_unicode_ci.
//   - PostgreSQL: TEXT instead of VARCHAR.
//   - Inserts batched 500 rows per statement; whole dump in one transaction.

import type { City, District, Region } from './load.js';

const BATCH = 500;

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Emit batched INSERT statements for one table. */
function insertBatches(table: string, columns: string[], rows: string[][]): string {
  const out: string[] = [];
  const colList = columns.join(', ');
  for (let i = 0; i < rows.length; i += BATCH) {
    const slice = rows.slice(i, i + BATCH);
    const values = slice.map((r) => `  (${r.join(', ')})`).join(',\n');
    out.push(`INSERT INTO ${table} (${colList}) VALUES\n${values};`);
  }
  return out.join('\n');
}

interface Dialect {
  header: (generatedAt: string) => string;
  begin: string;
  commit: string;
  schema: string;
}

const mysql: Dialect = {
  header: (generatedAt) =>
    `-- Generated by saudi-municipal-coding v1.0.0 at ${generatedAt}. Do not edit.\nSET NAMES utf8mb4;`,
  begin: 'START TRANSACTION;',
  commit: 'COMMIT;',
  schema: `DROP TABLE IF EXISTS saudi_district;
DROP TABLE IF EXISTS saudi_city;
DROP TABLE IF EXISTS saudi_region;

CREATE TABLE saudi_region (
  region_id INT UNSIGNED NOT NULL,
  name_ar VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  PRIMARY KEY (region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE saudi_city (
  city_id INT UNSIGNED NOT NULL,
  region_id INT UNSIGNED NOT NULL,
  name_ar VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  PRIMARY KEY (city_id),
  KEY idx_saudi_city_region (region_id),
  CONSTRAINT fk_saudi_city_region FOREIGN KEY (region_id) REFERENCES saudi_region (region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE saudi_district (
  district_id INT UNSIGNED NOT NULL,
  city_id INT UNSIGNED NOT NULL,
  region_id INT UNSIGNED NOT NULL,
  name_ar VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  PRIMARY KEY (district_id),
  KEY idx_saudi_district_region_city (region_id, city_id),
  KEY idx_saudi_district_city (city_id),
  CONSTRAINT fk_saudi_district_city FOREIGN KEY (city_id) REFERENCES saudi_city (city_id),
  CONSTRAINT fk_saudi_district_region FOREIGN KEY (region_id) REFERENCES saudi_region (region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;`,
};

const postgres: Dialect = {
  header: (generatedAt) =>
    `-- Generated by saudi-municipal-coding v1.0.0 at ${generatedAt}. Do not edit.`,
  begin: 'BEGIN;',
  commit: 'COMMIT;',
  schema: `DROP TABLE IF EXISTS saudi_district;
DROP TABLE IF EXISTS saudi_city;
DROP TABLE IF EXISTS saudi_region;

CREATE TABLE saudi_region (
  region_id BIGINT NOT NULL PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL
);

CREATE TABLE saudi_city (
  city_id BIGINT NOT NULL PRIMARY KEY,
  region_id BIGINT NOT NULL REFERENCES saudi_region (region_id),
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL
);

CREATE INDEX idx_saudi_city_region ON saudi_city (region_id);

CREATE TABLE saudi_district (
  district_id BIGINT NOT NULL PRIMARY KEY,
  city_id BIGINT NOT NULL REFERENCES saudi_city (city_id),
  region_id BIGINT NOT NULL REFERENCES saudi_region (region_id),
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL
);

CREATE INDEX idx_saudi_district_region_city ON saudi_district (region_id, city_id);
CREATE INDEX idx_saudi_district_city ON saudi_district (city_id);`,
};

function buildInserts(regions: Region[], cities: City[], districts: District[]): string {
  const regionRows = regions.map((r) => [
    String(r.region_id),
    sqlString(r.name_ar),
    sqlString(r.name_en),
  ]);
  const cityRows = cities.map((c) => [
    String(c.city_id),
    String(c.region_id),
    sqlString(c.name_ar),
    sqlString(c.name_en),
  ]);
  const districtRows = districts.map((d) => [
    String(d.district_id),
    String(d.city_id),
    String(d.region_id),
    sqlString(d.name_ar),
    sqlString(d.name_en),
  ]);

  return [
    insertBatches('saudi_region', ['region_id', 'name_ar', 'name_en'], regionRows),
    insertBatches('saudi_city', ['city_id', 'region_id', 'name_ar', 'name_en'], cityRows),
    insertBatches(
      'saudi_district',
      ['district_id', 'city_id', 'region_id', 'name_ar', 'name_en'],
      districtRows,
    ),
  ].join('\n\n');
}

function render(
  dialect: Dialect,
  generatedAt: string,
  regions: Region[],
  cities: City[],
  districts: District[],
): string {
  return [
    dialect.header(generatedAt),
    '',
    dialect.begin,
    '',
    dialect.schema,
    '',
    buildInserts(regions, cities, districts),
    '',
    dialect.commit,
    '',
  ].join('\n');
}

export function mysqlSql(
  generatedAt: string,
  regions: Region[],
  cities: City[],
  districts: District[],
): string {
  return render(mysql, generatedAt, regions, cities, districts);
}

export function postgresSql(
  generatedAt: string,
  regions: Region[],
  cities: City[],
  districts: District[],
): string {
  return render(postgres, generatedAt, regions, cities, districts);
}
